In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/world_population.csv")

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.head(5)

In [ ]:
df.index.values

In [74]:
mfd = pd.melt(df, id_vars=("Continent","Country/Territory","Capital", "2022 Population","Area (km²)" ) ) #Descompone un dataframe segun la columnas que le digamos

In [73]:
mfd

,Continent,Country/Territory,Capital,2022 Population,Area (km²),variable,False
0,Asia,Afghanistan,Kabul,41128771,652230,Rank,36
1,Europe,Albania,Tirana,2842321,28748,Rank,138
2,Africa,Algeria,Algiers,44903225,2381741,Rank,34
3,Oceania,American Samoa,Pago Pago,44273,199,Rank,213
4,Europe,Andorra,Andorra la Vella,79824,468,Rank,203
...,...,...,...,...,...,...,...
2803,Oceania,Wallis and Futuna,Mata-Utu,11572,142,World Population Percentage,0.0
2804,Africa,Western Sahara,El Aaiún,575986,266000,World Population Percentage,0.01
2805,Asia,Yemen,Sanaa,33696614,527968,World Population Percentage,0.42
2806,Africa,Zambia,Lusaka,20017675,752612,World Population Percentage,0.25
2807,Africa,Zimbabwe,Harare,16320537,390757,World Population Percentage,0.2

In [31]:
mfd.loc[0, "Capital"]

'Kabul'

In [37]:
multiindex = mfd.set_index(["Continent", "Country/Territory", "Capital", "Area (km²)", "2022 Population"]).sort_index()

In [39]:
multiindex

                                                                                       variable  \
Continent     Country/Territory Capital Area (km²) 2022 Population
Africa        Algeria           Algiers 2381741    44903225                                Rank
                                                   44903225                                CCA3
                                                   44903225                     2020 Population
                                                   44903225                     2015 Population
                                                   44903225                     2010 Population
...                                                                                         ...
South America Venezuela         Caracas 916445     28301696                     1980 Population
                                                   28301696                     1970 Population
                                                   28301696                   Density (per km²)
                                                   28301696                         Growth Rate
                                                   28301696         World Population Percentage

                                                                       value
Continent     Country/Territory Capital Area (km²) 2022 Population
Africa        Algeria           Algiers 2381741    44903225               34
                                                   44903225              DZA
                                                   44903225         43451666
                                                   44903225         39543154
                                                   44903225         35856344
...                                                                      ...
South America Venezuela         Caracas 916445     28301696         15210443
                                                   28301696         11355475
                                                   28301696           30.882
                                                   28301696           1.0036
                                                   28301696             0.35

[2808 rows x 2 columns]

In [28]:
multiindex.loc[:, ~multiindex.columns.isin(["Rank","World Population Percentage"])] #Ignorar ciertas columnas con "~" si se quita deja las ingresadas

                                                                       CCA3  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225         DZA
              Angola            Luanda      1246700    35588987         AGO
              Benin             Porto-Novo  112622     13352864         BEN
              Botswana          Gaborone    582000     2630296          BWA
              Burkina Faso      Ouagadougou 272967     22673762         BFA
...                                                                     ...
South America Paraguay          Asunción    406752     6780744          PRY
              Peru              Lima        1285216    34049588         PER
              Suriname          Paramaribo  163820     618040           SUR
              Uruguay           Montevideo  181034     3422794          URY
              Venezuela         Caracas     916445     28301696         VEN

                                                                        2020 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                43451666
              Angola            Luanda      1246700    35588987                33428485
              Benin             Porto-Novo  112622     13352864                12643123
              Botswana          Gaborone    582000     2630296                  2546402
              Burkina Faso      Ouagadougou 272967     22673762                21522626
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  6618695
              Peru              Lima        1285216    34049588                33304756
              Suriname          Paramaribo  163820     618040                    607065
              Uruguay           Montevideo  181034     3422794                  3429086
              Venezuela         Caracas     916445     28301696                28490453

                                                                        2015 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                39543154
              Angola            Luanda      1246700    35588987                28127721
              Benin             Porto-Novo  112622     13352864                10932783
              Botswana          Gaborone    582000     2630296                  2305171
              Burkina Faso      Ouagadougou 272967     22673762                18718019
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  6177950
              Peru              Lima        1285216    34049588                30711863
              Suriname          Paramaribo  163820     618040                    575475
              Uruguay           Montevideo  181034     3422794                  3402818
              Venezuela         Caracas     916445     28301696                30529716

                                                                        2010 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                35856344
              Angola            Luanda      1246700    35588987                23364185
              Benin             Porto-Novo  112622     13352864                 9445710
              Botswana          Gaborone    582000     2630296                  2091664
              Burkina Faso      Ouagadougou 272967     22673762                16116845
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  5768613
              Peru              Lima        1285216    34049588                29229572
              Suriname          Paramaribo  163820     618040                    546080
              Uruguay           Montevideo  181034     3422794                  3352651
              Venezuela         Caracas     916445     28301696                28715022

                                                                        2000 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                30774621
              Angola            Luanda      1246700    35588987                16394062
              Benin             Porto-Novo  112622     13352864                 6998023
              Botswana          Gaborone    582000     2630296                  1726985
              Burkina Faso      Ouagadougou 272967     22673762                11882888
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  5123819
              Peru              Lima        1285216    34049588                26654439
              Suriname          Paramaribo  163820     618040                    478998
              Uruguay           Montevideo  181034     3422794                  3292224
              Venezuela         Caracas     916445     28301696                24427729

                                                                        1990 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                25518074
              Angola            Luanda      1246700    35588987                11828638
              Benin             Porto-Novo  112622     13352864                 5133419
              Botswana          Gaborone    582000     2630296                  1341474
              Burkina Faso      Ouagadougou 272967     22673762                 9131361
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  4059195
              Peru              Lima        1285216    34049588                22109099
              Suriname          Paramaribo  163820     618040                    412756
              Uruguay           Montevideo  181034     3422794                  3117012
              Venezuela         Caracas     916445     28301696                19750579

                                                                        1980 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                18739378
              Angola            Luanda      1246700    35588987                 8330047
              Benin             Porto-Novo  112622     13352864                 3833939
              Botswana          Gaborone    582000     2630296                   938578
              Burkina Faso      Ouagadougou 272967     22673762                 6932967
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  3078912
              Peru              Lima        1285216    34049588                17492406
              Suriname          Paramaribo  163820     618040                    375112
              Uruguay           Montevideo  181034     3422794                  2953750
              Venezuela         Caracas     916445     28301696                15210443

                                                                        1970 Population  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                13795915
              Angola            Luanda      1246700    35588987                 6029700
              Benin             Porto-Novo  112622     13352864                 3023443
              Botswana          Gaborone    582000     2630296                   592244
              Burkina Faso      Ouagadougou 272967     22673762                 5611666
...                                                                                 ...
South America Paraguay          Asunción    406752     6780744                  2408787
              Peru              Lima        1285216    34049588                13562371
              Suriname          Paramaribo  163820     618040                    379918
              Uruguay           Montevideo  181034     3422794                  2790265
              Venezuela         Caracas     916445     28301696                11355475

                                                                        Density (per km²)  \
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225                   18.8531
              Angola            Luanda      1246700    35588987                   28.5466
              Benin             Porto-Novo  112622     13352864                  118.5635
              Botswana          Gaborone    582000     2630296                     4.5194
              Burkina Faso      Ouagadougou 272967     22673762                   83.0641
...                                                                                   ...
South America Paraguay          Asunción    406752     6780744                    16.6705
              Peru              Lima        1285216    34049588                   26.4933
              Suriname          Paramaribo  163820     618040                      3.7727
              Uruguay           Montevideo  181034     3422794                    18.9069
              Venezuela         Caracas     916445     28301696                   30.8820

                                                                        Growth Rate
Continent     Country/Territory Capital     Area (km²) 2022 Population
Africa        Algeria           Algiers     2381741    44903225              1.0164
              Angola            Luanda      1246700    35588987              1.0315
              Benin             Porto-Novo  112622     13352864              1.0274
              Botswana          Gaborone    582000     2630296               1.0162
              Burkina Faso      Ouagadougou 272967     22673762              1.0259
...                                                                             ...
South America Paraguay          Asunción    406752     6780744               1.0115
              Peru              Lima        1285216    34049588              1.0099
              Suriname          Paramaribo  163820     618040                1.0082
              Uruguay           Montevideo  181034     3422794               0.9990
              Venezuela         Caracas     916445     28301696              1.0036

[234 rows x 10 columns]

In [77]:
tff = multiindex.loc[:, multiindex.columns.isin([])] #Ignorar todas las columnas restantes

In [78]:
tff

Empty DataFrame
Columns: []
Index: [(Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Algeria, Algiers, 2381741, 44903225), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Angola, Luanda, 1246700, 35588987), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Benin, Porto-Novo, 112622, 13352864), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Botswana, Gaborone, 582000, 2630296), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burkina Faso, Ouagadougou, 272967, 22673762), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Burundi, Bujumbura, 27834, 12889576), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cameroon, Yaounde, 475442, 27914536), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Cape Verde, Praia, 4033, 593149), (Africa, Central African Republic, Bangui, 622984, 5579144), (Africa, Central African Republic, Bangui, 622984, 5579144), (Africa, Central African Republic, Bangui, 622984, 5579144), (Africa, Central African Republic, Bangui, 622984, 5579144), ...]

[2808 rows x 0 columns]